version: '3'

services:
  web:
    image: ${DOCKER_IMAGE}
    restart: always
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      WEB_APPLICATION_PORT: ${WEB_APPLICATION_PORT}
      WEB_APPLICATION_URL: ${WEB_APPLICATION_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      ALLOWED_IP: ${ALLOWED_IP}
      FORCE_INSTALLER: ${FORCE_INSTALLER}
    volumes:
    - ./docker/web/backups:/usr/src/scientilla/backups
    - ./docker/web/installer/uploads:/usr/src/scientilla/installer/uploads
    - ./docker/web/metrics_import:/usr/src/scientilla/metrics_import
    - ./docker/web/logs:/usr/src/scientilla/logs
    - ./docker/web/certs:/certs
    - ${PWD}/docker/web/config/scientilla.js:/usr/src/scientilla/config/scientilla.js
    - ${PWD}/docker/web/config/local.js:/usr/src/scientilla/config/local.js
    - ${PWD}/docker/web/config/customizations.js:/usr/src/scientilla/config/customizations.js
    - ${PWD}/docker/web/config/connectors.js:/usr/src/scientilla/config/connectors.js
    ports:
    - "${WEB_APPLICATION_PORT}:1337"
    depends_on:
    - db
  db:
    image: postgres:10
    restart: always
    volumes:
    - ./docker/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
    - "${DATABASE_PORT}:5432"

volumes:
  scientillapgdata: