version: '3'

services:
  web:
    environment:
      NODE_ENV: development
    command:
    - sh
    - -c
    - |
      if [ "$FORCE_INSTALLER" == "true" ]; then
          npm run installer force
      else
          npm run installer
      fi