version: '3'

services:
  web:
    build:
      context: .
    restart: always
    ports:
    - "${SAILS_PORT}:1337"
    depends_on:
    - db
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    restart: always
    volumes:
    - scientillapgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - "${DB_PORT}:5432"

volumes:
  scientillapgdata: